# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' My median
#'
#' @param x Vector of Numeric values
#' @inheritParams stats::median
#'
#' @return
#' Median of vector x
#' @export
#'
#' @examples
#gen_effect_calibration
