# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Generate beta matrix giving genetic effect per SNP on taxa abundances.
#' @importFrom glue glue
#' @importFrom tibble tibble
#' @importFrom purrr map
#' @importFrom magrittr %>%
#' 
#' @inheritParams gen_effect_calibration
#' 
#' @param n_b Number of taxa
#' @param n_g Number of SNPs
#' @param n_clust A vector with a length matching the total number of taxa with values from 0 to the number of clusters. Typically the [assign_taxa()] output.
#' @param n_qtl_o Number of causative QTL on taxa abundances (per taxon)
#' @param n_otus Number of taxa under genetic control.
#' @param effect_size Vector giving the size of genetic effect to try
#' @param correlation A numeric value between 0 and 1 representing the target correlation between taxa within the same cluster.
#' @param beta_info Informations from Beta matrix of genetic effects
#' 
#' @return 
#' A `list` of two objects linked to the beta matrix. 
#' The beta matrix itself : a `matrix` of taxa (in rows) across SNPs (in columns) giving the multiplicative effect of genotype on taxa abundances.
#' A small `data.frame` containing the parameters used during the beta matrix simulation, including `cluster`, `id_otu` and `id_qtl_o`.
#' 
#' @seealso [compute_beta_g()], [holo_simu()]
#' 
#' @rdname compute_beta_matrix_cluster

compute_beta_matrix_cluster <- function(n_b,
                                        n_g,
                                        n_clust,
                                        n_qtl_o,
                                        n_otus, #percentage
                                        effect_size = 1,
                                        correlation = 1, ## value between 0 and 1
                                        beta_info = NULL
){
  # Initialisation of beta matrix of genetic effects
  beta <- matrix(0, nrow = n_b, ncol = n_g, 
                 dimnames = list(
                   glue('OTU_{1:n_b}'), 
                   glue('SNP_{1:n_g}') 
                 ))
  
  nb_k <- (n_clust[n_clust != 0] %>% unique() %>% length())  
  
  if(is.null(beta_info)){
    beta_info <- tibble(
      cluster     = 1:nb_k,
      id_otu      = split(1:length(n_clust), n_clust)[-1],
      id_qtl_o    = map(cluster, \(x) {sample(1:n_g, n_qtl_o)})
    )
  }
  sd_factor <- effect_size / sqrt(n_qtl_o)
  for(clus in 1:nb_k){
    # Extract causal SNPs for current cluster
    id_qtl_o <- beta_info[["id_qtl_o"]][clus][[1]]
    # Extract OTUs under genetic control for current cluster
    ID_OTUs_gen <- beta_info[["id_otu"]][clus][[1]]
    # fill beta with random variable 
    # TODO: should the effect of a SNP be shared across OTU in a cluster ?
    # to create blockwise effect in beta G ? 
    lambda <- root(correlation)
    ind_coef         <- rnorm(length(ID_OTUs_gen) * n_qtl_o, mean = 0, sd = sd_factor)
    correlated_coef  <- matrix(rnorm(n_qtl_o, 0, sd_factor), 
                               nrow = length(ID_OTUs_gen), ncol = n_qtl_o,
                               byrow = TRUE)
    beta[ID_OTUs_gen,id_qtl_o] <- (lambda * correlated_coef + (1 - lambda) * ind_coef) / sqrt(lambda^2 + (1-lambda)^2)
  }
  
  beta <- list(matrix = beta,
               sim_params = beta_info)
  
  return(beta)
}
