# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Compute the mean for each taxa across population
#'
#' This function estimate the mean microbiome by averaging abundances across individuals for each taxa. Optionally, 
#' it use a Dirichlet distribution to simulate inter-individual variability centered arround the mean.
#' 
#' @importFrom dirmult rdirichlet
#' @importFrom magrittr %>%
#' 
#' @param microbiome A `matrix` of microbiome abundances (taxa in rows, individuals in columns).
#' @param dir A `logical`; if `TRUE`, use a Dirichlet distribution to simulate inter-individual variability. Default is `FALSE`.
#' @param n_ind The number of individuals to simulate with the Dirichlet distribution (required if `dir = TRUE`).
#' @param ao A numeric scalar used as the concentration parameter for the Dirichlet distribution.
#' @param mix.params A numeric vector (`length = 2`) specifying weights between Dirichlet samples and the original mean. The weigths should sum to 1.
#' 
#' @return
#' A `numeric`vector of mean microbiome values if `dir = FALSE`.
#' A `matrix` of simulated microbiomes if `dir = TRUE`
#' 
#' @seealso [compute_current_microbiome()]
#' @rdname compute_mean_microbiome

compute_mean_microbiome <- function(microbiome, dir = F, n_ind = NULL, ao, mix.params){
  mean_microbiome <- rowMeans(microbiome)
  if(dir){
    if (is.null(n_ind)){
      stop("`n_ind` must be provided when `dir = TRUE`")
    }
    
    dir_mean <- rdirichlet(n_ind,as.numeric(mean_microbiome)*ao) %>% t()
    mix_mean <- (mix.params[1] * dir_mean + mix.params[2] * matrix(mean_microbiome,nrow=nrow(dir_mean),ncol=ncol(dir_mean),byrow=F))
    attr(mix_mean, "dirichlet") <- dir_mean
    return(mix_mean)
  }else{
    mean_microbiome
  }
}
