# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute product of matrixes based on few parameters
#' 
#' This function compute the product between the matrix of OTUs-specific genetic effects and the matrix of genotypes. 
#' This is part of [gen_effect_calibration()], where individual_level effects of genotypes on taxa are computed.
#' 
#' @importFrom magrittr %>%
#'
#' @param beta A `matrix` of taxa (in rows) across SNPs (in columns) giving the multiplicative effect of genotype on taxa abundances. Typically obtained from [compute_beta_matrix_cluster()].
#' @param genotypes A `matrix` of genotypes with SNPs in rows and individuals in columns.
#' @param noise A `numeric` scalar indicating the standard deviation of the Gaussian noise to add.
#' @param taxa_scale A `numeric` scalar to scale the noise added to each OTUs abundance.
#' 
#' @seealso [gen_effect_calibration()]

#' @return A `matrix` with taxa in roxs and individuals in columns, where each element represents the abundance of a given taxa in an individual, influenced by the genotype.
#' 
#' @rdname compute_beta_g
#' @examples
#' set.seed(123)
#' n_taxa <- 5
#' n_snp <- 10
#' n_ind <- 50
#' # Simulate a little beta matrix
#' beta <- matrix(sample(seq(0.1, 1, by = 0.05), size = n_taxa*n_snp, replace = TRUE), nrow = n_taxa, ncol = n_snp)
#'
#' # Simulate a little genotype matrix
#' genotypes <- matrix(sample(0:2, size = n_snp*n_ind, replace = TRUE), nrow = n_snp, ncol = n_ind)
#'
#' # Compute beta_g matrix with noise
#' beta_g <- RITHMS:::compute_beta_g(beta = beta,
#'                                   genotypes = genotypes,
#'                                   noise = 0.05,
#'                                   taxa_scale = 1)
compute_beta_g <- function(beta,
                           genotypes,
                           noise,
                           taxa_scale){
  G <- genotypes
  beta_g_tmp <- beta %*% G
  beta_g <- beta_g_tmp %>% t() %>% scale(center=TRUE,scale=FALSE) %>% t() 
  beta_g_raw <- beta_g
  noise_vec = rnorm(n = nrow(beta) * ncol(G), sd = noise) * taxa_scale
  beta_g <-  beta_g_raw + noise_vec
  attr(beta_g,"noise") <- list('noise' = noise_vec,'betag' = beta_g_raw)
  return(beta_g)
}
