# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' @importFrom compositions clr
#' @importFrom purrr pluck
#' @importFrom tibble as_tibble
#' @importFrom magrittr %>%
#' 
#' Useful function to extract microbiomes from RITHMS output
#' 
#' @export
#' 
#' @examples
#' library(magrittr)
#' library(purrr)
#'
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25,
#'                               b2 = 0.25,
#'                               founder_object = ToyData,
#'                               n_clust = taxa_assign_g,
#'                               n_ind = 500,
#'                               verbose = FALSE,
#'                               noise.microbiome = 0.5,
#'                               effect.size = 0.3,
#'                               lambda = 0.5,
#'                               dir = TRUE,
#'                               selection = FALSE,
#'                               seed = 1234)
#'
#' # To extract CLR abundances of the G1 generation microbiome
#' G1_microbiome <- get_microbiomes(generations_simu$G1, CLR = TRUE)
#'
#' # To extract all the relative abundances of microbiomes from all generations
#' # substract metadata
#' microbiomes <- generations_simu[-1] %>% map(get_microbiomes)
#'
#' # To extract mean phenotypes of all generations
#' mean_phenotypes <- generations_simu[-1] %>% map(get_mean_phenotypes)
#'
#' # To extract phenotypic values for each individual of generation G1
#' G1_phenotypes_values <- get_phenotypes_value(generations_simu$G1)
#'
#' # To extract the phenotype of each generation as the combined effects of microbiota and direct genetic effects
#' phenotypes <- generations_simu[-1] %>% map(get_phenotypes)
#'
#' # To extract omega beta G values for each individual of generation G1
#' G1_om_beta_g <- get_om_beta_g(generations_simu$G1)
#'
#' # To extract ID of selected individuals to each generation
#' selected_inds <- generations_simu[-1] %>% map(get_selected_ind) 
#'
#' # To extract Shannon diversity
#' # First step, compute richness from abundances
#' richness_from_abundances <- generations_simu[-1] %>% map(get_microbiomes) %>% map(richness_from_abundances_gen)
#' shannon_diversity <- richness_from_abundances %>% map(get_mean_diversity)
get_microbiomes <- function(data, transpose = F, CLR = F) {
  if(transpose){
    if(CLR){
      return(data |> pluck("microbiome") |> t() |> replace_zero() |> clr() |> as.data.frame())
    }else{
      return(data |> pluck("microbiome") |> t() |> as.data.frame())
    }
  }
  data |> pluck("microbiome") |> as.data.frame()
}

#' Useful function to extract mean phenotype values from RITHMS output
#'
#' @export
get_mean_phenotypes <- function(data) {
  data |> pluck("phenotypes","y") |> mean()
}

#' Useful function to extract phenotype values from RITHMS output ("gq" by default)
#'
#' @export
get_phenotypes_value <- function(data, value = "gq") {
  data |> pluck("phenotypes",value)
}

#' Useful function to extract omega beta G values from RITHMS output
#'
#' @export
get_om_beta_g <- function(data) {
  data |> pluck("omega_beta_g")
}

#' Useful function to extract ID of selected individuals from RITHMS output
#'
#' @export
get_selected_ind <- function(data) {
  data |> pluck("ID_selected")
}

#' Useful function to extract all phenotype values as data frame from RITHMS output
#'
#' @export
get_phenotypes <- function(data) {
  data |> pluck("phenotypes") |> as.data.frame() |> as_tibble(rownames = "ID") 
}

#' Useful function to extract Shannon diversity from RITHMS output
#'
#' @export
get_mean_diversity <- function(data) {
  mean(data$Shannon)
}
