# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Useful function to extract microbiomes from RITHMS output
#' 
#' The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_microbiomes` extract the microbiome abundance matrix from a generation object, with or without CLR transformation or transposition.
#' 
#' @importFrom compositions clr
#' @importFrom purrr pluck
#' @importFrom tibble as_tibble
#' @importFrom magrittr %>%
#' 
#' @param data List corresponding to one generation, as returned by `holo_simu()`. Containing simulation output.
#' @param transpose Logical; if `TRUE`, transpose the microbiome matrix (OTUs in rows, individuals in columns).
#' @param CLR Logical; if `TRUE`, applies a CLR transformation to the abundance data. This transformation requires `transpose = TRUE`.
#' 
#' @return A `data.frame`containing the microbiome abundances of individuals. Default, individuals are in rows and OTUs in columns. Change `transpose`parameter if needed.
#' 
#' @examples
#' library(magrittr)
#' library(purrr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'
#' # Extract microbiome matrix for G1 generation
#' G1_microbiome <- get_microbiomes(generations_simu$G1)
#'
#' # Extract with transposition
#' G1_t_microbiome <- get_microbiomes(generations_simu$G1, transpose = TRUE)
#'
#' # Extract with CLR transformation
#' G1_CLR_microbiome <- get_microbiomes(generations_simu$G1, transpose = TRUE, CLR = TRUE)
#'
#' # Extract all microbiome matrices of all generations
#' # substract metadata
#' microbiomes <- generations_simu[-1] %>% map(get_microbiomes)
#'
#' library(magrittr)
#' library(purrr)
#'
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25,
#'                               b2 = 0.25,
#'                               founder_object = ToyData,
#'                               n_clust = taxa_assign_g,
#'                               n_ind = 500,
#'                               verbose = FALSE,
#'                               noise.microbiome = 0.5,
#'                               effect.size = 0.3,
#'                               lambda = 0.5,
#'                               dir = TRUE,
#'                               selection = FALSE,
#'                               seed = 1234)
#'
#' # To extract CLR abundances of the G1 generation microbiome
#' G1_microbiome <- get_microbiomes(generations_simu$G1, CLR = TRUE)
#'
#' # To extract all the relative abundances of microbiomes from all generations
#' # substract metadata
#' microbiomes <- generations_simu[-1] %>% map(get_microbiomes)
#'
#' # To extract mean phenotypes of all generations
#' mean_phenotypes <- generations_simu[-1] %>% map(get_mean_phenotypes)
#'
#' # To extract phenotypic values for each individual of generation G1
#' G1_phenotypes_values <- get_phenotypes_value(generations_simu$G1)
#'
#' # To extract the phenotype of each generation as the combined effects of microbiota and direct genetic effects
#' phenotypes <- generations_simu[-1] %>% map(get_phenotypes)
#'
#' # To extract omega beta G values for each individual of generation G1
#' G1_om_beta_g <- get_om_beta_g(generations_simu$G1)
#'
#' # To extract ID of selected individuals to each generation
#' selected_inds <- generations_simu[-1] %>% map(get_selected_ind) 
#'
#' # To extract Shannon diversity
#' # First step, compute richness from abundances
#' richness_from_abundances <- generations_simu[-1] %>% map(get_microbiomes) %>% map(richness_from_abundances_gen)
#' shannon_diversity <- richness_from_abundances %>% map(get_mean_diversity)
#' @seealso [get_mean_phenotypes()], [get_phenotypes_value()], [get_om_beta_g()], [get_selected_ind()], [get_phenotypes()]
#' @rdname get_microbiomes
#' @export
get_microbiomes <- function(data, transpose = F, CLR = F) {
  if(transpose){
    if(CLR){
      return(data |> pluck("microbiome") |> t() |> replace_zero() |> clr() |> as.data.frame())
    }else{
      return(data |> pluck("microbiome") |> t() |> as.data.frame())
    }
  }
  data |> pluck("microbiome") |> as.data.frame()
}

#' Useful function to extract mean phenotype values from RITHMS output
#'
#' The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_mean_phenotypes`extract average phenotype from a generation object.
#'
#' @param data List corresponding to one generation, as returned by [holo_simu()]. Containing simulation output.
#' @return The mean phenotype value for a given generation.
#' @examples
#' library(purrr)
#' library(magrittr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'                               
#' # Extract mean phenotype value for G1 generation
#' G1_mean_phenotype <- get_mean_phenotypes(generations_simu$G1)
#' 
#' # Extract mean phenotype values of all generations
#' ## Don't forget to substract the metadata
#' mean_phenotypes <- generations_simu[-1] %>% map(get_mean_phenotypes)
#' 
#' @seealso [get_microbiomes()], [get_phenotypes_value()], [get_om_beta_g()], [get_selected_ind()], [get_phenotypes()]
#' @rdname get_mean_phenotypes
#' @export
get_mean_phenotypes <- function(data) {
  data |> pluck("phenotypes","y") |> mean()
}

#' Useful function to extract phenotype values from RITHMS output ("gq" by default)
#' 
#' The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_phenotypes_values` extract the set of phenotype values from a generation object.
#' 
#' @param data List corresponding to one generation, as returned by [holo_simu()]. Containing simulation output.
#' @return A `data.frame` of phenotype values for each individuals of a given generation.
#' 
#' @examples
#' library(magrittr)
#' library(purrr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'                               
#'  #Extract phenotype values for each individuals of G1 generation
#'  G1_phenotypes_values <- get_phenotypes_value(generations_simu$G1)
#'  
#'  #Extract phenotype values for each individuals of all generations
#'  ## Don't forget to substract the metadata
#'  phenotypes_values <- generations_simu[-1] %>% map(get_phenotypes_value)
#'  
#' @seealso [get_mean_phenotypes()], [get_microbiomes()], [get_om_beta_g()], [get_selected_ind()], [get_phenotypes()]
#' @rdname get_phenotypes_value
#' @export
get_phenotypes_value <- function(data, value = "gq") {
  data |> pluck("phenotypes",value)
}

#' Useful function to extract omega beta G values from RITHMS output
#' 
#' The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_om_beta_g`extract omega beta G values from a generation object.
#' 
#' @param data List corresponding to one generation, as returned by [holo_simu()]. Containing simulation output.
#' @return A `data.frame` of omega beta G values for each individuals of a given generation.
#' 
#' @examples
#' library(magrittr)
#' library(purrr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'                               
#' #Extract omega beta G values for each individuals of G1 generation
#' G1_om_beta_g <- get_om_beta_g(generations_simu$G1)
#'  
#' #Extract omega beta G values for each individuals of all generations
#' ## Don't forget to substract the metadata
#' om_beta_g <- generations_simu[-1] %>% map(get_om_beta_g)
#'  
#' @seealso [get_mean_phenotypes()], [get_phenotypes_value()], [get_microbiomes()], [get_selected_ind()], [get_phenotypes()]
#' @rdname get_om_beta_g
#' @export
get_om_beta_g <- function(data) {
  data |> pluck("omega_beta_g")
}

#' Useful function to extract ID of selected individuals from RITHMS output
#'
#'The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_selected_ind`extract selectd individuals IDs from a generation object.
#' 
#' @param data List corresponding to one generation, as returned by [holo_simu()]. Containing simulation output.
#' 
#' @return A`list` of the selected individuals of a given generation.
#' @examples
#' library(magrittr)
#' library(purrr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'                               
#' #Extract selected individuals IDs for the G1 generation
#' G1_selected_ind <- get_selected_ind(generations_simu$G1)
#'  
#' #Extract selected individuals IDs for all generations
#' ## Don't forget to substract the metadata
#' selected_ind <- generations_simu[-1] %>% map(get_selected_ind)
#' 
#' @seealso [get_mean_phenotypes()], [get_phenotypes_value()], [get_om_beta_g()], [get_microbiomes()], [get_phenotypes()]
#' @rdname get_selected_ind
#' @export
get_selected_ind <- function(data) {
  data |> pluck("ID_selected")
}

#' Useful function to extract all phenotype values as data frame from RITHMS output
#' 
#' The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_phenotypes`extract phenotype for each individuals as the combined effects of microbiota and direct genetic effects, from a generation object.
#' 
#' @param data List corresponding to one generation, as returned by [holo_simu()]. Containing simulation output.
#' @return A `data.frame` of phenotype for each individuals of a given generation. Phenotype values are given as the result of the combined effects of the microbiota and direct genetic effects.
#' 
#' @examples
#' library(magrittr)
#' library(purrr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'                               
#' #Extract phenotypes of the G1 generation
#' G1_phenotypes <- get_phenotypes(generations_simu$G1)
#'  
#' #Extract phenotypes for all generations
#' ## Don't forget to substract the metadata
#' phenotypes <- generations_simu[-1] %>% map(get_phenotypes)
#' 
#' @seealso [get_mean_phenotypes()], [get_phenotypes_value()], [get_om_beta_g()], [get_selected_ind()], [get_microbiomes()]
#' @rdname get_phenotypes
#' @export
get_phenotypes <- function(data) {
  data |> pluck("phenotypes") |> as.data.frame() |> as_tibble(rownames = "ID") 
}

#' Useful function to extract Shannon diversity from RITHMS output
#' 
#' The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_mean_diversity`extract the average Shannon diversity from a generation object.
#' 
#' @note This function requires a previous call to [richness_from_abundances_gen()] to compute different types of diversity within the generation.
#' 
#' @param data List corresponding to one generation, as returned by [holo_simu()]. Containing simulation output.
#' @return The average Shannon diversity within a given generation.
#' 
#' @examples
#' library(magrittr)
#' library(purrr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'                               
#' # Extract Shannon diversity for each generations
#' ## First step, compute richness from abundances
#' richness_from_abundances <- generations_simu[-1] %>% map(get_microbiomes) %>% map(richness_from_abundances_gen)
#' mean_shannon_diversity <- richness_from_abundances %>% map(get_mean_diversity)
#' 
#' @seealso [get_microbiomes()], [richness_from_abundances_gen()]
#' @rdname get_mean_diversity
#' @export
get_mean_diversity <- function(data) {
  mean(data$Shannon)
}
