# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Useful function to extract phenotype values from RITHMS output ("gq" by default)
#' 
#' The gets functions use the output of [holo_simu()] to extract the information of interest from a given generation.
#' `get_phenotypes_values` extract the set of phenotype values from a generation object.
#' 
#' @importFrom purrr pluck
#' @importFrom magrittr %>%
#' 
#' @param data List corresponding to one generation, as returned by [holo_simu()]. Containing simulation output.
#' @param value A String caracter that precise the object to extract from the generation object. Must be "gq" to extract phenotype values.
#' @return A `data.frame` of phenotype values for each individuals of a given generation.
#' 
#' @examples
#' \dontrun{
#' library(magrittr)
#' library(purrr)
#' datafile <- system.file("DeruPop.rds", package = "RITHMS")
#' ToyData <- readRDS(datafile)
#' taxa_assign_g <- assign_taxa(founder_object = ToyData)
#' generations_simu <- holo_simu(h2 = 0.25, b2 = 0.25, founder_object = ToyData,
#'                               n_clust = taxa_assign_g, n_ind = 500,
#'                               verbose = FALSE, seed = 1234)
#'                               
#'  #Extract phenotype values for each individuals of G1 generation
#'  G1_phenotypes_values <- get_phenotypes_value(generations_simu$G1)
#'  
#'  #Extract phenotype values for each individuals of all generations
#'  ## Don't forget to substract the metadata
#'  phenotypes_values <- generations_simu[-1] %>% map(get_phenotypes_value)
#'  }
#'  
#' @seealso [get_mean_phenotypes()], [get_microbiomes()], [get_om_beta_g()], [get_selected_ind()], [get_phenotypes()]
#' @rdname get_phenotypes_value
#' @export
get_phenotypes_value <- function(data, value = "gq") {
  data |> pluck("phenotypes",value)
}
