# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Rarefaction step within read_input_data
#' 
#' @importFrom tibble as_tibble column_to_rownames tibble with
#' @importFrom dplyr rename filter pull
#' @importFrom MoBPS creating.diploid
#' @importFrom magrittr %>%
#' 
#' @inheritParams read_input_data
#' 
#' @param microbiome_matrix Microbiome counting table, OTUs in columns and a column specifying the IDs
#' @param id_column String specifying the name of the column containing the individual IDs. Default is "ind_id"
#' @param threshold Minimum prevalence threshold
#' 
#' @return
#' The filtered microbiome matrix, without OTUs whose prevalence is lower than the set threshold
#' 
#' @seealso [read_input_data()], [generate_founder()]
#' 
#' @rdname rarefied_microbiome
#' @examples
#' \dontrun{
#'   microbiome <- data.table::fread("/path/to/microbiome.txt")
#'   microbiome_filtered <- rarefied_microbiome(microbiome, id_columns = "sample_id", threshold = 0.05)
#' }

rarefied_microbiome <- function(microbiome_matrix,
                                id_column = "ind_id",
                                threshold = 0.05){
  microbiome_matrix <- microbiome_matrix |> as_tibble() |> column_to_rownames(var = id_column)
  abundant_otus <- tibble(
    V1         = colnames(microbiome_matrix),
    prevalence = colMeans(microbiome_matrix > 0)
  ) |> rename(OTU = V1) |> filter(prevalence >= threshold) |> pull(OTU)
  return(microbiome_matrix[, abundant_otus])
}
