# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Rarefaction step within read_input_data
#' @importFrom tibble as_tibble column_to_rownames tibble
#' @importFrom dplyr rename filter pull
#' @importFrom MoBPS creating.diploid
#' 
#' @inheritParams read_input_data
#' @noRd
rarefied_microbiome <- function(microbiome_matrix, 
                                threshold = 0.05){
  microbiome_matrix <- microbiome_matrix |> as_tibble() |> column_to_rownames("numero_individu")
  abundant_otus <- tibble(
    V1         = colnames(microbiome_matrix),
    prevalence = colMeans(microbiome_matrix > 0)
  ) |> rename(OTU = V1) |> filter(prevalence >= threshold) |> pull(OTU)
  return(microbiome_matrix[, abundant_otus])
}

#' Formatting of ped and map files into haplotypes table and filter individuals
#'
#' @inheritParams read_input_data
generate_founder <- function(path = NULL,
                             microbiote_matrix){
  # # Convert PED-file into haplotype dataset (one haplotype per colum)
  if(is.null(path)){
    stop("path must be a valid string like : '/path/to/directory/prefix'")
  }else{
    if(FALSE %in% file_test("-f", c(glue("{path}.ped"),
                                    glue("{path}.map")))){
      stop(glue("Files {path}.ped and/or {path}.map don't exist, please check your path argument"))
    }else{
      map <- as.matrix(read.table(glue("{path}.map")))
      ped <- as.matrix(read.table(glue("{path}.ped")))
      #Step to filter ped map based on microbiome matrix,
      #rownames microbiote_matrix must be ind ID to match column 2 of ped file
      ped_ind <- ped[,2] %>% gsub("\\s","",.)
      microbiote_ind <- rownames(microbiote_matrix)
      microbiote_filtered <- microbiote_matrix[microbiote_ind %in% ped_ind,]
      ped <- ped[ped_ind %in% microbiote_ind,]
      ####
      nsnp <- (ncol(ped)-6)/2
      haplo1 <- ped[,1:nsnp*2+6-1] #all odd numbers
      haplo2 <- ped[,1:nsnp*2+6] #all uneven numbers
      haplo <- t(rbind(haplo1, haplo2)[c(0,nrow(haplo1)) + sort(rep(1:nrow(haplo1),2)),])
      #haplo <- ifelse(haplo == "0", NA,haplo)
      population <- creating.diploid(dataset = haplo, map = map, verbose=verbose)
      attr(microbiote_filtered,"population") <- population
      return(microbiote_filtered)
    }
  }
}


#' Formatting data from file paths to base population object
#'
#' @param path_to_microbiome String giving the path to count table file
#' @param path_to_pedmap String giving the path and prefix to ped and map file
#' @param threshold Threshold for rarefaction, DEFAULT = 0.05
#' @param ind_selected Vector of string values with individuals to keep, have to match rownames of count table file, DEFAULT = NULL
#' 
#' @importFrom data.table fread
#' @importFrom dplyr filter
#' @importFrom glue glue
#' @importFrom magrittr %>%
#' 
#' @return
#' A data.frame corresponding to (rarefied) microbiome with individuals in rows and taxa in columns. Genotypes data.frame is an attribute called "population" reachable using attr(output_name,"population")
#' @export
read_input_data <- function(path_to_microbiome,
                            path_to_pedmap,
                            threshold = 0.05,
                            ind_selected = NULL){
  ########
  #read microbiome file and make genotypes and microbiome data match according to individuals
  ########
  microbiome <- data.table::fread(path_to_microbiome)
  microbiome_filtered5 <- rarefied_microbiome(microbiome, threshold = threshold)
  if(!is.null(ind_selected)){
    microbiome_filtered5 <- microbiome_filtered5 %>% filter(rownames(.) %in% ind_selected)
  }
  founder_object <- generate_founder(path = glue::glue("{path_to_pedmap}"),
                                     microbiome_filtered5)
  return(founder_object)
}


