# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Formatting data from file paths to base population object
#'
#' @importFrom data.table fread
#' @importFrom dplyr filter
#' @importFrom glue glue
#' @importFrom magrittr %>%
#'
#' @param path_to_microbiome String giving the path to count table file
#' @param path_to_pedmap String giving the path and prefix to ped and map file
#' @param biome_id_column String specifying the name of the column containing the individual IDs for the microbiome matrix. Default is "ind_id".
#' @param threshold Threshold for rarefaction, DEFAULT = 0.05
#' @param ind_selected Vector of string values with individuals to keep, have to match rownames of count table file, DEFAULT = NULL
#' 
#' @return
#' A data.frame corresponding to (rarefied) microbiome with individuals in rows and taxa in columns. Genotypes data.frame is an attribute called "population" reachable using `attr(output_name,"population")`
#' 
#' @rdname read_input_data
#' @export
#' @examples
#' # founder_object <- read_input_data(path_to_microbiome = "/path/to/microbiome/'prefix'",
#' #                                   path_to_pedmap = "/path/to/pedmap/'prefix'",
#' #                                   biome_id_column = "ind_id",
#' #                                   threshold = 0.05,
#' #                                   ind_selected = NULL)
#'
read_input_data <- function(path_to_microbiome,
                            path_to_pedmap,
                            biome_id_column = "ind_id",
                            threshold = 0.05,
                            ind_selected = NULL){
  ########
  #read microbiome file and make genotypes and microbiome data match according to individuals
  ########
  microbiome <- data.table::fread(path_to_microbiome)
  microbiome_filtered5 <- rarefied_microbiome(microbiome, id_column = biome_id_column, threshold = threshold)
  if(!is.null(ind_selected)){
    microbiome_filtered5 <- microbiome_filtered5 %>% filter(rownames(.) %in% ind_selected)
  }
  founder_object <- generate_founder(path = glue::glue("{path_to_pedmap}"),
                                     microbiome_filtered5)
  return(founder_object)
}


