# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Compute root value for beta matrix construction
#' 
#' This function computes the parameter used to build a beta matrix with a given correlation structure between taxa. It is used in the beta matrix construction.
#' 
#' @param rho A numeric value between 0 and 1 representing the target correlation between taxa within the same cluster. This parameter is used to induce correlation in the beta matrix.
#' @rdname root
#' 
root <- function(rho) {
  if (rho == 0.5) return(0.5)
  (2 * rho - sqrt(4 * rho^2 - 4 * rho * (2* rho - 1))) / (4*rho - 2)
}
