# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Obtain id of the parents selected for the next generation based on the criteria chosen by the user
#' 
#' @importFrom magrittr %>%
#' @importFrom dplyr select
#' @importFrom stringr str_extract
#' 
#' @param phenotypes Phenotype values of the current generation given as the result of the combined effects of the microbiota and direct genetic effects. Typically [get_phenotypes()] output or [compute_phenotypes()].
#' @param microbiomes Abundances for each individual of the current generation. Note: It is necessary to transform the abundances if they are CLR-transformed with the following command. `microbiomes_clr |>  t() |> clrInv() |> t()`
#' @param genotypes Genotypes values of the current generation. Typically from the MoBPS `get.geno()` function.
#' @param beta Beta matrix from [compute_beta_matrix_cluster()] output.
#' @param beta_otu Omega parameter from [calibrate_params_phenotypes()] output.
#' 
#' @inheritParams holo_simu
#' @rdname select_individual

select_individual <- function(phenotypes,
                              microbiomes,
                              genotypes,
                              beta,
                              beta_otu,
                              selection, 
                              size_selection_F, 
                              size_selection_M, 
                              selection_type,
                              size_rmultinom,
                              w.param){
  #extract id of individuals of interest
  n_F <- (size_selection_F * length(grep("^F",colnames(genotypes)))) |> round()
  n_M <- (size_selection_M * length(grep("^M",colnames(genotypes)))) |> round()
  
  #being able to select between GB, B, G, diversity or diversity + GB
  if(selection){
    ######
    #Few tests on parameters values
    #####
    if(is.null(size_selection_F) || is.null(size_selection_M)){
      print("Please check you provided size_selection_F and size_selection_M argument (int) for selection step")
    }
   if(!selection_type %in% c("GB", "B", "G", "diversity", "div.GB")){
     print("Selection type must be one of 'GB', 'B', 'G', 'diversity' or 'div.GB'")
   }
    if(selection_type == "GB"){
      score <- phenotypes$gq + as.vector(beta_otu %*% (beta[rowSums(beta) != 0, ] %*% genotypes))
      #score <- phenotypes$gq + as.vector((beta[rowSums(beta) != 0, ] %*% genotypes))
      #score <- phenotypes$gq + phenotypes$gb
    }else if(selection_type == "G"){
      score <- phenotypes$gq
    }else if(selection_type == "B"){
      score <- phenotypes$gb
    }else if(selection_type == "diversity"){
      score <- microbiomes %>% richness_from_abundances_gen(size_rmultinom = size_rmultinom) %>% select(Shannon) %>% as.matrix()
    }else{
      diversity <- microbiomes %>% richness_from_abundances_gen(size_rmultinom = size_rmultinom) %>% select(Shannon) %>% as.matrix()
      TBV <- phenotypes$gq + as.vector(beta_otu %*% (beta[rowSums(beta) != 0, ] %*% genotypes))
      score = w.param[1] * diversity + w.param[2] * TBV
    }
    
    #extract individuals ID
    F_id <- score[grep("^F",rownames(score)),] %>% sort(decreasing = T) %>% names() %>% str_extract("[0-9]+") %>% head(n_F)
    M_id <- score[grep("^M",rownames(score)),] %>% sort(decreasing = T) %>% names() %>% str_extract("[0-9]+") %>% head(n_M)
    
  }else{
    if(!is.null(size_selection_F) || !is.null(size_selection_M)){
      print("Warning : Selection is set to False but size_selection_F or size_selection_M is not NULL")
    }
    
    n_F <- (0.3 * length(grep("^F",colnames(genotypes)))) |> round()
    n_M <- (0.3 * length(grep("^M",colnames(genotypes)))) |> round()
    #extract individuals ID
    F_id <- colnames(genotypes)[grep("^F",colnames(genotypes))] %>% str_extract("[0-9]+") %>% sample(n_F)
    M_id <- colnames(genotypes)[grep("^M",colnames(genotypes))] %>% str_extract("[0-9]+") %>% sample(n_M)
  }

  return(list(F_id = F_id, M_id = M_id))
}
