# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Taxonomy assignation
#' 
#' @format A `data.frame` containing the taxonomy for each OTU sequenced matching the ID in the microbiota matrix till Kingdom level.
#' 
#' @source [Déru et al.](https://pmc.ncbi.nlm.nih.gov/articles/PMC9194801/) for microbiota data and corresponding metadata
#' 
#' 
"taxonomy"
